-- AlterTable
ALTER TABLE "ExtraPurchase" ALTER COLUMN "tabaccoPyi" SET DEFAULT 0,
ALTER COLUMN "tabaccoPyi" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Formula" ALTER COLUMN "tabaccoPyi" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "PayOtherItem" ALTER COLUMN "tabaccoPyi" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "TypeOfCheroot" ALTER COLUMN "price" SET DEFAULT 0,
ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "TypeOfFilterSize" ALTER COLUMN "price" SET DEFAULT 0,
ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "TypeOfLabel" ALTER COLUMN "price" SET DEFAULT 0,
ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "TypeOfLeaf" ALTER COLUMN "price" SET DEFAULT 0,
ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "TypeOfTabacco" ALTER COLUMN "price" SET DEFAULT 0,
ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION;
